package com.vpon.mapping

import org.scalatest.{MustMatchers, FlatSpec}

import com.vpon.mapping.exception.CarrierMappingException

class CarrierMappingTest extends FlatSpec with MustMatchers {

  it must "find VponCarrier properly by mcc and mnc coming from UA DB" in {
    CarrierMapping.findVponCarrierByMccAndMnc("466", "01") must be(VponCarrier(17, "Taiwan", "FarEasTone"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "05") must be(VponCarrier(3, "Taiwan", "APTG"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "06") must be(VponCarrier(17, "Taiwan", "FarEasTone"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "11") must be(VponCarrier(12, "Taiwan", "Chunghwa"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "88") must be(VponCarrier(17, "Taiwan", "FarEasTone"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "89") must be(VponCarrier(29, "Taiwan", "VIBO"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "92") must be(VponCarrier(12, "Taiwan", "Chunghwa"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "93") must be(VponCarrier(28, "Taiwan", "Taiwan Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "97") must be(VponCarrier(28, "Taiwan", "Taiwan Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("466", "99") must be(VponCarrier(28, "Taiwan", "Taiwan Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "00") must be(VponCarrier(5, "China", "China Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "01") must be(VponCarrier(9, "China", "China Unicom"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "02") must be(VponCarrier(5, "China", "China Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "03") must be(VponCarrier(7, "China", "China Telecom"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "05") must be(VponCarrier(7, "China", "China Telecom"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "06") must be(VponCarrier(9, "China", "China Unicom"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "07") must be(VponCarrier(5, "China", "China Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("460", "20") must be(VponCarrier(8, "China", "China Tietong"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "00") must be(VponCarrier(16, "Japan", "eMobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "01") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "02") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "03") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "04") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "06") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "07") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "08") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "09") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "10") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "11") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "12") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "13") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "14") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "15") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "16") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "17") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "18") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "19") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "20") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "21") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "22") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "23") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "24") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "25") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "26") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "27") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "28") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "29") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "30") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "31") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "32") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "33") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "34") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "35") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "36") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "37") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "38") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "39") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "40") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "41") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "42") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "43") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "44") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "45") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "46") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "47") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "48") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "49") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "50") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "51") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "52") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "53") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "54") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "55") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "56") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "58") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "60") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "61") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "62") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "63") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "64") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "65") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "66") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "67") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "68") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "69") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "70") must be(VponCarrier(4, "Japan", "au"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "71") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "72") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "73") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "74") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "75") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "76") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "77") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "78") must be(VponCarrier(22, "Japan", "Okinawa Cellular Telephone"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "79") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "87") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "88") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "89") must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "90") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "92") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "93") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "94") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "95") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "96") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "97") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "98") must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierByMccAndMnc("440", "99") must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "00") must be(VponCarrier(2, "Hong Kong", "1O1O / One2Free / New World Mobility"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "01") must be(VponCarrier(13, "Hong Kong", "CITIC Telecom 1616"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "02") must be(VponCarrier(15, "Hong Kong", "CSL Limited"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "03") must be(VponCarrier(1, "Hong Kong", "3"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "04") must be(VponCarrier(1, "Hong Kong", "3"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "05") must be(VponCarrier(1, "Hong Kong", "3"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "06") must be(VponCarrier(25, "Hong Kong", "SmarTone"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "07") must be(VponCarrier(10, "Hong Kong", "China Unicom (Hong Kong) Limited"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "09") must be(VponCarrier(6, "Hong Kong", "China Motion Telecom"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "10") must be(VponCarrier(20, "Hong Kong", "New World Mobility"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "11") must be(VponCarrier(11, "Hong Kong", "China-Hong Kong Telecom"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "12") must be(VponCarrier(14, "Hong Kong", "CMCC HK"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "13") must be(VponCarrier(14, "Hong Kong", "CMCC HK"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "14") must be(VponCarrier(18, "Hong Kong", "Hutchison Telecom"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "15") must be(VponCarrier(26, "Hong Kong", "SmarTone Mobile Communications Limited"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "16") must be(VponCarrier(24, "Hong Kong", "PCCW Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "17") must be(VponCarrier(26, "Hong Kong", "SmarTone Mobile Communications Limited"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "18") must be(VponCarrier(15, "Hong Kong", "CSL Limited"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "19") must be(VponCarrier(24, "Hong Kong", "PCCW Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "22") must be(VponCarrier(23, "Hong Kong", "P Plus"))
    CarrierMapping.findVponCarrierByMccAndMnc("454", "29") must be(VponCarrier(24, "Hong Kong", "PCCW Mobile"))
    CarrierMapping.findVponCarrierByMccAndMnc("*", "*") must be(VponCarrier(0, "Others", ""))
  }

  it must "find VponCarrier properly by id" in {
    CarrierMapping.findVponCarrierById(0) must be(VponCarrier(0, "Others", ""))
    CarrierMapping.findVponCarrierById(1) must be(VponCarrier(1, "Hong Kong", "3"))
    CarrierMapping.findVponCarrierById(2) must be(VponCarrier(2, "Hong Kong", "1O1O / One2Free / New World Mobility"))
    CarrierMapping.findVponCarrierById(3) must be(VponCarrier(3, "Taiwan", "APTG"))
    CarrierMapping.findVponCarrierById(4) must be(VponCarrier(4, "Japan", "au"))
    CarrierMapping.findVponCarrierById(5) must be(VponCarrier(5, "China", "China Mobile"))
    CarrierMapping.findVponCarrierById(6) must be(VponCarrier(6, "Hong Kong", "China Motion Telecom"))
    CarrierMapping.findVponCarrierById(7) must be(VponCarrier(7, "China", "China Telecom"))
    CarrierMapping.findVponCarrierById(8) must be(VponCarrier(8, "China", "China Tietong"))
    CarrierMapping.findVponCarrierById(9) must be(VponCarrier(9, "China", "China Unicom"))
    CarrierMapping.findVponCarrierById(10) must be(VponCarrier(10, "Hong Kong", "China Unicom (Hong Kong) Limited"))
    CarrierMapping.findVponCarrierById(11) must be(VponCarrier(11, "Hong Kong", "China-Hong Kong Telecom"))
    CarrierMapping.findVponCarrierById(12) must be(VponCarrier(12, "Taiwan", "Chunghwa"))
    CarrierMapping.findVponCarrierById(13) must be(VponCarrier(13, "Hong Kong", "CITIC Telecom 1616"))
    CarrierMapping.findVponCarrierById(14) must be(VponCarrier(14, "Hong Kong", "CMCC HK"))
    CarrierMapping.findVponCarrierById(15) must be(VponCarrier(15, "Hong Kong", "CSL Limited"))
    CarrierMapping.findVponCarrierById(16) must be(VponCarrier(16, "Japan", "eMobile"))
    CarrierMapping.findVponCarrierById(17) must be(VponCarrier(17, "Taiwan", "FarEasTone"))
    CarrierMapping.findVponCarrierById(18) must be(VponCarrier(18, "Hong Kong", "Hutchison Telecom"))
    CarrierMapping.findVponCarrierById(19) must be(VponCarrier(19, "Japan", "KDDI"))
    CarrierMapping.findVponCarrierById(20) must be(VponCarrier(20, "Hong Kong", "New World Mobility"))
    CarrierMapping.findVponCarrierById(21) must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierById(21) must be(VponCarrier(21, "Japan", "NTT docomo"))
    CarrierMapping.findVponCarrierById(22) must be(VponCarrier(22, "Japan", "Okinawa Cellular Telephone"))
    CarrierMapping.findVponCarrierById(23) must be(VponCarrier(23, "Hong Kong", "P Plus"))
    CarrierMapping.findVponCarrierById(24) must be(VponCarrier(24, "Hong Kong", "PCCW Mobile"))
    CarrierMapping.findVponCarrierById(25) must be(VponCarrier(25, "Hong Kong", "SmarTone"))
    CarrierMapping.findVponCarrierById(26) must be(VponCarrier(26, "Hong Kong", "SmarTone Mobile Communications Limited"))
    CarrierMapping.findVponCarrierById(27) must be(VponCarrier(27, "Japan", "SoftBank"))
    CarrierMapping.findVponCarrierById(28) must be(VponCarrier(28, "Taiwan", "Taiwan Mobile"))
    CarrierMapping.findVponCarrierById(29) must be(VponCarrier(29, "Taiwan", "VIBO"))

    an [CarrierMappingException] should be thrownBy CarrierMapping.findVponCarrierById(-999)
  }

  it must "find all VponCarriers properly" in {
    CarrierMapping.findAllVponCarriers().size must be(30)
  }

  it must "provide warmUp method" in {
    try {
      CarrierMapping.warmUp()
    } catch {
      case e: Throwable => fail("should provide warmUp method")
    }
  }
}
