package com.vpon.mapping

import org.scalatest.{MustMatchers, FlatSpec}

class LanguageMappingTest extends FlatSpec with MustMatchers {

  it must "provide warmUp method" in {
    try {
      LanguageMapping.warmUp()
    } catch {
      case e: Throwable => fail("should provide warmUp method")
    }
  }

  it must "find Vpon Language properly from language code and locale of iso by mapping" in {
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "cn") must be(VponLanguage(1, "Chinese (Simplified)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "sg") must be(VponLanguage(1, "Chinese (Simplified)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "hans") must be(VponLanguage(1, "Chinese (Simplified)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "CHS") must be(VponLanguage(1, "Chinese (Simplified)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "tw") must be(VponLanguage(2, "Chinese (Traditional)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "hk") must be(VponLanguage(2, "Chinese (Traditional)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "mo") must be(VponLanguage(2, "Chinese (Traditional)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "hant") must be(VponLanguage(2, "Chinese (Traditional)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "CHT") must be(VponLanguage(2, "Chinese (Traditional)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zh", "*") must be(VponLanguage(12, "Chinese (including Simplified & Traditional)"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "au") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "bz") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "ca") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "cb") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "gb") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "in") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "ie") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "jm") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "nz") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "ph") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "za") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "tt") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "us") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "*") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fil", "*") must be(VponLanguage(4, "Filipino"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fr", "fr") must be(VponLanguage(5, "French"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fr", "lu") must be(VponLanguage(5, "French"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fr", "ch") must be(VponLanguage(5, "French"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fr", "ca") must be(VponLanguage(5, "French"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fr", "be") must be(VponLanguage(5, "French"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fr", "*") must be(VponLanguage(5, "French"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("id", "*") must be(VponLanguage(6, "Indonesian"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ja", "*") must be(VponLanguage(7, "Japanese"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ko", "*") must be(VponLanguage(8, "Korean"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("th", "*") must be(VponLanguage(10, "Thai"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("vi", "*") must be(VponLanguage(11, "Vietnamese"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("aa", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ab", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("af", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ak", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sq", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("am", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ar", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("an", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("hy", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("as", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("av", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ae", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ay", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("az", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("bm", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ba", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("eu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("be", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("bn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("bh", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("bi", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("bs", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("br", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("bg", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("my", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ca", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ch", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ce", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ny", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("cv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kw", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("co", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("cr", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("hr", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("cs", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("da", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("dv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("nl", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("dz", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("eo", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("et", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ee", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fo", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fj", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fi", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ff", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("gl", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ka", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("de", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("el", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("gn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("gu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ht", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ha", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("he", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("hz", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("hi", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ho", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("hu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ia", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ie", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ga", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ig", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ik", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("io", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("is", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("it", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("iu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("jv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kl", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kr", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ks", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kk", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("km", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ki", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("rw", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ky", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kg", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ku", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("kj", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("la", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("lb", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("lg", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("li", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ln", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("lo", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("lt", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("lu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("lv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("gv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("mk", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("mg", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ms", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ml", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("mt", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("mi", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("mr", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("mh", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("mn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("na", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("nv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("nd", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ne", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ng", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("nb", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("nn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("no", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ii", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("nr", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("oc", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("oj", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("cu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("om", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("or", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("os", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("pa", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("pi", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fa", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("pl", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ps", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("pt", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("qu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("rm", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("rn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ro", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ru", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sa", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sc", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sd", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("se", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sm", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sg", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sr", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("gd", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("si", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sk", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sl", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("so", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("st", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("es", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("su", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sw", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ss", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("sv", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ta", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("te", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("tg", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ti", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("bo", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("tk", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("tl", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("tn", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("to", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("tr", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ts", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("tt", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("tw", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ty", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ug", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("uk", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ur", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("uz", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("ve", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("vo", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("wa", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("cy", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("wo", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("fy", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("xh", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("yi", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("yo", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("za", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("zu", "*") must be(VponLanguage(0, "Others"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("*", "*") must be(VponLanguage(0, "Others"))

    // not existed
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("en", "##") must be(VponLanguage(3, "English"))
    LanguageMapping.findVponLanguageByLanguageCodeAndLocale("@@", "##") must be(VponLanguage(0, "Others"))
  }

  it must "find all Vpon Languages properly" in {
    LanguageMapping.findAllVponLanguages().size must be(12)
  }
}
