package com.vpon.mapping

import org.scalatest.{MustMatchers, FlatSpec}

class UniversalCategoryMappingTest extends FlatSpec with MustMatchers {

  it must "provide warmUp method" in {
    try {
      UniversalCategoryMapping.warmUp()
    } catch {
      case e: Throwable => fail("should provide warmUp method")
    }
  }

  it must "find Vpon UniversalCategory properly by id" in {
    UniversalCategoryMapping.findVponUniversalCategoryById(1) must be(VponUniversalCategory(1, "Arts & Entertainment", "", "IAB1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(27) must be(VponUniversalCategory(27, "Arts & Entertainment", "Books & Literature", "IAB1-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(28) must be(VponUniversalCategory(28, "Arts & Entertainment", "Celebrity Fan/Gossip", "IAB1-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(29) must be(VponUniversalCategory(29, "Arts & Entertainment", "Fine Art", "IAB1-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(30) must be(VponUniversalCategory(30, "Arts & Entertainment", "Humor", "IAB1-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(31) must be(VponUniversalCategory(31, "Arts & Entertainment", "Movies", "IAB1-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(32) must be(VponUniversalCategory(32, "Arts & Entertainment", "Music", "IAB1-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(33) must be(VponUniversalCategory(33, "Arts & Entertainment", "Television", "IAB1-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(2) must be(VponUniversalCategory(2, "Automotive", "", "IAB2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(34) must be(VponUniversalCategory(34, "Automotive", "Auto Parts", "IAB2-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(35) must be(VponUniversalCategory(35, "Automotive", "Auto Repair", "IAB2-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(36) must be(VponUniversalCategory(36, "Automotive", "Buying/Selling Cars", "IAB2-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(37) must be(VponUniversalCategory(37, "Automotive", "Car Culture", "IAB2-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(38) must be(VponUniversalCategory(38, "Automotive", "Certified Pre-Owned", "IAB2-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(39) must be(VponUniversalCategory(39, "Automotive", "Convertible", "IAB2-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(40) must be(VponUniversalCategory(40, "Automotive", "Coupe", "IAB2-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(41) must be(VponUniversalCategory(41, "Automotive", "Crossover", "IAB2-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(42) must be(VponUniversalCategory(42, "Automotive", "Diesel", "IAB2-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(43) must be(VponUniversalCategory(43, "Automotive", "Electric Vehicle", "IAB2-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(44) must be(VponUniversalCategory(44, "Automotive", "Hatchback", "IAB2-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(45) must be(VponUniversalCategory(45, "Automotive", "Hybrid", "IAB2-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(46) must be(VponUniversalCategory(46, "Automotive", "Luxury", "IAB2-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(47) must be(VponUniversalCategory(47, "Automotive", "MiniVan", "IAB2-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(48) must be(VponUniversalCategory(48, "Automotive", "Motorcycles", "IAB2-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(49) must be(VponUniversalCategory(49, "Automotive", "Off-Road Vehicles", "IAB2-16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(50) must be(VponUniversalCategory(50, "Automotive", "Performance Vehicles", "IAB2-17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(51) must be(VponUniversalCategory(51, "Automotive", "Pickup", "IAB2-18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(52) must be(VponUniversalCategory(52, "Automotive", "Road-Side Assistance", "IAB2-19"))
    UniversalCategoryMapping.findVponUniversalCategoryById(53) must be(VponUniversalCategory(53, "Automotive", "Sedan", "IAB2-20"))
    UniversalCategoryMapping.findVponUniversalCategoryById(54) must be(VponUniversalCategory(54, "Automotive", "Trucks & Accessories", "IAB2-21"))
    UniversalCategoryMapping.findVponUniversalCategoryById(55) must be(VponUniversalCategory(55, "Automotive", "Vintage Cars", "IAB2-22"))
    UniversalCategoryMapping.findVponUniversalCategoryById(56) must be(VponUniversalCategory(56, "Automotive", "Wagon", "IAB2-23"))
    UniversalCategoryMapping.findVponUniversalCategoryById(3) must be(VponUniversalCategory(3, "Business", "", "IAB3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(57) must be(VponUniversalCategory(57, "Business", "Advertising", "IAB3-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(58) must be(VponUniversalCategory(58, "Business", "Agriculture", "IAB3-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(59) must be(VponUniversalCategory(59, "Business", "Biotech/Biomedical", "IAB3-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(60) must be(VponUniversalCategory(60, "Business", "Business Software", "IAB3-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(61) must be(VponUniversalCategory(61, "Business", "Construction", "IAB3-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(62) must be(VponUniversalCategory(62, "Business", "Forestry", "IAB3-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(63) must be(VponUniversalCategory(63, "Business", "Government", "IAB3-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(64) must be(VponUniversalCategory(64, "Business", "Green Solutions", "IAB3-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(65) must be(VponUniversalCategory(65, "Business", "Human Resources", "IAB3-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(66) must be(VponUniversalCategory(66, "Business", "Logistics", "IAB3-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(67) must be(VponUniversalCategory(67, "Business", "Marketing", "IAB3-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(68) must be(VponUniversalCategory(68, "Business", "Metals", "IAB3-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(4) must be(VponUniversalCategory(4, "Careers", "", "IAB4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(69) must be(VponUniversalCategory(69, "Careers", "Career Planning", "IAB4-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(70) must be(VponUniversalCategory(70, "Careers", "College", "IAB4-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(71) must be(VponUniversalCategory(71, "Careers", "Financial Aid", "IAB4-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(72) must be(VponUniversalCategory(72, "Careers", "Job Fairs", "IAB4-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(73) must be(VponUniversalCategory(73, "Careers", "Job Search", "IAB4-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(74) must be(VponUniversalCategory(74, "Careers", "Resume Writing/Advice", "IAB4-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(75) must be(VponUniversalCategory(75, "Careers", "Nursing", "IAB4-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(76) must be(VponUniversalCategory(76, "Careers", "Scholarships", "IAB4-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(77) must be(VponUniversalCategory(77, "Careers", "Telecommuting", "IAB4-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(78) must be(VponUniversalCategory(78, "Careers", "U.S. Military", "IAB4-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(79) must be(VponUniversalCategory(79, "Careers", "Career Advice", "IAB4-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(5) must be(VponUniversalCategory(5, "Education", "", "IAB5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(80) must be(VponUniversalCategory(80, "Education", "7-12 Education", "IAB5-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(81) must be(VponUniversalCategory(81, "Education", "Adult Education", "IAB5-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(82) must be(VponUniversalCategory(82, "Education", "Art History", "IAB5-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(83) must be(VponUniversalCategory(83, "Education", "Colledge Administration", "IAB5-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(84) must be(VponUniversalCategory(84, "Education", "College Life", "IAB5-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(85) must be(VponUniversalCategory(85, "Education", "Distance Learning", "IAB5-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(86) must be(VponUniversalCategory(86, "Education", "English as a 2nd Language", "IAB5-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(87) must be(VponUniversalCategory(87, "Education", "Language Learning", "IAB5-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(88) must be(VponUniversalCategory(88, "Education", "Graduate School", "IAB5-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(89) must be(VponUniversalCategory(89, "Education", "Homeschooling", "IAB5-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(90) must be(VponUniversalCategory(90, "Education", "Homework/Study Tips", "IAB5-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(91) must be(VponUniversalCategory(91, "Education", "K-6 Educators", "IAB5-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(92) must be(VponUniversalCategory(92, "Education", "Private School", "IAB5-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(93) must be(VponUniversalCategory(93, "Education", "Special Education", "IAB5-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(94) must be(VponUniversalCategory(94, "Education", "Studying Business", "IAB5-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(6) must be(VponUniversalCategory(6, "Family & Parenting", "", "IAB6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(95) must be(VponUniversalCategory(95, "Family & Parenting", "Adoption", "IAB6-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(96) must be(VponUniversalCategory(96, "Family & Parenting", "Babies & Toddlers", "IAB6-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(97) must be(VponUniversalCategory(97, "Family & Parenting", "Daycare/Pre School", "IAB6-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(98) must be(VponUniversalCategory(98, "Family & Parenting", "Family Internet", "IAB6-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(99) must be(VponUniversalCategory(99, "Family & Parenting", "Parenting - K-6 Kids", "IAB6-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(100) must be(VponUniversalCategory(100, "Family & Parenting", "Parenting Teens", "IAB6-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(101) must be(VponUniversalCategory(101, "Family & Parenting", "Pregnancy", "IAB6-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(102) must be(VponUniversalCategory(102, "Family & Parenting", "Special Needs Kids", "IAB6-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(103) must be(VponUniversalCategory(103, "Family & Parenting", "Eldercare", "IAB6-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(7) must be(VponUniversalCategory(7, "Health & Fitness", "", "IAB7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(104) must be(VponUniversalCategory(104, "Health & Fitness", "Exercise", "IAB7-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(105) must be(VponUniversalCategory(105, "Health & Fitness", "A.D.D.", "IAB7-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(106) must be(VponUniversalCategory(106, "Health & Fitness", "AIDS/HIV", "IAB7-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(107) must be(VponUniversalCategory(107, "Health & Fitness", "Allergies", "IAB7-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(108) must be(VponUniversalCategory(108, "Health & Fitness", "Alternative Medicine", "IAB7-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(109) must be(VponUniversalCategory(109, "Health & Fitness", "Arthritis", "IAB7-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(110) must be(VponUniversalCategory(110, "Health & Fitness", "Asthma", "IAB7-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(111) must be(VponUniversalCategory(111, "Health & Fitness", "Autism/PDD", "IAB7-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(112) must be(VponUniversalCategory(112, "Health & Fitness", "Bipolar Disorder", "IAB7-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(113) must be(VponUniversalCategory(113, "Health & Fitness", "Brain Tumor", "IAB7-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(114) must be(VponUniversalCategory(114, "Health & Fitness", "Cancer", "IAB7-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(115) must be(VponUniversalCategory(115, "Health & Fitness", "Cholesterol", "IAB7-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(116) must be(VponUniversalCategory(116, "Health & Fitness", "Chronic Fatigue Syndrome", "IAB7-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(117) must be(VponUniversalCategory(117, "Health & Fitness", "Chronic Pain", "IAB7-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(118) must be(VponUniversalCategory(118, "Health & Fitness", "Cold & Flu", "IAB7-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(119) must be(VponUniversalCategory(119, "Health & Fitness", "Deafness", "IAB7-16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(120) must be(VponUniversalCategory(120, "Health & Fitness", "Dental Care", "IAB7-17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(121) must be(VponUniversalCategory(121, "Health & Fitness", "Depression", "IAB7-18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(122) must be(VponUniversalCategory(122, "Health & Fitness", "Dermatology", "IAB7-19"))
    UniversalCategoryMapping.findVponUniversalCategoryById(123) must be(VponUniversalCategory(123, "Health & Fitness", "Diabetes", "IAB7-20"))
    UniversalCategoryMapping.findVponUniversalCategoryById(124) must be(VponUniversalCategory(124, "Health & Fitness", "Epilepsy", "IAB7-21"))
    UniversalCategoryMapping.findVponUniversalCategoryById(125) must be(VponUniversalCategory(125, "Health & Fitness", "GERD/Acid Reflux", "IAB7-22"))
    UniversalCategoryMapping.findVponUniversalCategoryById(126) must be(VponUniversalCategory(126, "Health & Fitness", "Headaches/Migraines", "IAB7-23"))
    UniversalCategoryMapping.findVponUniversalCategoryById(127) must be(VponUniversalCategory(127, "Health & Fitness", "Heart Disease", "IAB7-24"))
    UniversalCategoryMapping.findVponUniversalCategoryById(128) must be(VponUniversalCategory(128, "Health & Fitness", "Herbs for Health", "IAB7-25"))
    UniversalCategoryMapping.findVponUniversalCategoryById(129) must be(VponUniversalCategory(129, "Health & Fitness", "Holistic Healing", "IAB7-26"))
    UniversalCategoryMapping.findVponUniversalCategoryById(130) must be(VponUniversalCategory(130, "Health & Fitness", "IBS/Crohn's Disease", "IAB7-27"))
    UniversalCategoryMapping.findVponUniversalCategoryById(131) must be(VponUniversalCategory(131, "Health & Fitness", "Incest/Abuse Support", "IAB7-28"))
    UniversalCategoryMapping.findVponUniversalCategoryById(132) must be(VponUniversalCategory(132, "Health & Fitness", "Incontinence", "IAB7-29"))
    UniversalCategoryMapping.findVponUniversalCategoryById(133) must be(VponUniversalCategory(133, "Health & Fitness", "Infertility", "IAB7-30"))
    UniversalCategoryMapping.findVponUniversalCategoryById(134) must be(VponUniversalCategory(134, "Health & Fitness", "Men's Health", "IAB7-31"))
    UniversalCategoryMapping.findVponUniversalCategoryById(135) must be(VponUniversalCategory(135, "Health & Fitness", "Nutrition", "IAB7-32"))
    UniversalCategoryMapping.findVponUniversalCategoryById(136) must be(VponUniversalCategory(136, "Health & Fitness", "Orthopedics", "IAB7-33"))
    UniversalCategoryMapping.findVponUniversalCategoryById(137) must be(VponUniversalCategory(137, "Health & Fitness", "Panic/Anxiety Disorders", "IAB7-34"))
    UniversalCategoryMapping.findVponUniversalCategoryById(138) must be(VponUniversalCategory(138, "Health & Fitness", "Pediatrics", "IAB7-35"))
    UniversalCategoryMapping.findVponUniversalCategoryById(139) must be(VponUniversalCategory(139, "Health & Fitness", "Physical Therapy", "IAB7-36"))
    UniversalCategoryMapping.findVponUniversalCategoryById(140) must be(VponUniversalCategory(140, "Health & Fitness", "Psychology/Psychiatry", "IAB7-37"))
    UniversalCategoryMapping.findVponUniversalCategoryById(141) must be(VponUniversalCategory(141, "Health & Fitness", "Senior Health", "IAB7-38"))
    UniversalCategoryMapping.findVponUniversalCategoryById(142) must be(VponUniversalCategory(142, "Health & Fitness", "Sexuality", "IAB7-39"))
    UniversalCategoryMapping.findVponUniversalCategoryById(143) must be(VponUniversalCategory(143, "Health & Fitness", "Sleep Disorders", "IAB7-40"))
    UniversalCategoryMapping.findVponUniversalCategoryById(144) must be(VponUniversalCategory(144, "Health & Fitness", "Smoking Cessation", "IAB7-41"))
    UniversalCategoryMapping.findVponUniversalCategoryById(145) must be(VponUniversalCategory(145, "Health & Fitness", "Substance Abuse", "IAB7-42"))
    UniversalCategoryMapping.findVponUniversalCategoryById(146) must be(VponUniversalCategory(146, "Health & Fitness", "Thyroid Disease", "IAB7-43"))
    UniversalCategoryMapping.findVponUniversalCategoryById(147) must be(VponUniversalCategory(147, "Health & Fitness", "Weight Loss", "IAB7-44"))
    UniversalCategoryMapping.findVponUniversalCategoryById(148) must be(VponUniversalCategory(148, "Health & Fitness", "Women's Health", "IAB7-45"))
    UniversalCategoryMapping.findVponUniversalCategoryById(8) must be(VponUniversalCategory(8, "Food & Drink", "", "IAB8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(149) must be(VponUniversalCategory(149, "Food & Drink", "American Cuisine", "IAB8-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(150) must be(VponUniversalCategory(150, "Food & Drink", "Barbecues & Grilling", "IAB8-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(151) must be(VponUniversalCategory(151, "Food & Drink", "Cajun/Creole", "IAB8-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(152) must be(VponUniversalCategory(152, "Food & Drink", "Chinese Cuisine", "IAB8-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(153) must be(VponUniversalCategory(153, "Food & Drink", "Cocktails/Beer", "IAB8-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(154) must be(VponUniversalCategory(154, "Food & Drink", "Coffee/Tea", "IAB8-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(155) must be(VponUniversalCategory(155, "Food & Drink", "Cuisine-Specific", "IAB8-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(156) must be(VponUniversalCategory(156, "Food & Drink", "Desserts & Baking", "IAB8-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(157) must be(VponUniversalCategory(157, "Food & Drink", "Dining Out", "IAB8-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(158) must be(VponUniversalCategory(158, "Food & Drink", "Food Allergies", "IAB8-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(159) must be(VponUniversalCategory(159, "Food & Drink", "French Cuisine", "IAB8-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(160) must be(VponUniversalCategory(160, "Food & Drink", "Health/Lowfat Cooking", "IAB8-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(161) must be(VponUniversalCategory(161, "Food & Drink", "Italian Cuisine", "IAB8-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(162) must be(VponUniversalCategory(162, "Food & Drink", "Japanese Cuisine", "IAB8-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(163) must be(VponUniversalCategory(163, "Food & Drink", "Mexican Cuisine", "IAB8-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(164) must be(VponUniversalCategory(164, "Food & Drink", "Vegan", "IAB8-16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(165) must be(VponUniversalCategory(165, "Food & Drink", "Vegetarian", "IAB8-17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(166) must be(VponUniversalCategory(166, "Food & Drink", "Wine", "IAB8-18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(9) must be(VponUniversalCategory(9, "Hobbies & Interests", "", "IAB9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(167) must be(VponUniversalCategory(167, "Hobbies & Interests", "Art/Technology", "IAB9-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(168) must be(VponUniversalCategory(168, "Hobbies & Interests", "Arts & Crafts", "IAB9-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(169) must be(VponUniversalCategory(169, "Hobbies & Interests", "Beadwork", "IAB9-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(170) must be(VponUniversalCategory(170, "Hobbies & Interests", "Birdwatching", "IAB9-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(171) must be(VponUniversalCategory(171, "Hobbies & Interests", "Board Games/Puzzles", "IAB9-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(172) must be(VponUniversalCategory(172, "Hobbies & Interests", "Candle & Soap Making", "IAB9-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(173) must be(VponUniversalCategory(173, "Hobbies & Interests", "Card Games", "IAB9-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(174) must be(VponUniversalCategory(174, "Hobbies & Interests", "Chess", "IAB9-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(175) must be(VponUniversalCategory(175, "Hobbies & Interests", "Cigars", "IAB9-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(176) must be(VponUniversalCategory(176, "Hobbies & Interests", "Collecting", "IAB9-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(177) must be(VponUniversalCategory(177, "Hobbies & Interests", "Comic Books", "IAB9-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(178) must be(VponUniversalCategory(178, "Hobbies & Interests", "Drawing/Sketching", "IAB9-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(179) must be(VponUniversalCategory(179, "Hobbies & Interests", "Freelance Writing", "IAB9-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(180) must be(VponUniversalCategory(180, "Hobbies & Interests", "Genealogy", "IAB9-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(181) must be(VponUniversalCategory(181, "Hobbies & Interests", "Getting Published", "IAB9-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(182) must be(VponUniversalCategory(182, "Hobbies & Interests", "Guitar", "IAB9-16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(183) must be(VponUniversalCategory(183, "Hobbies & Interests", "Home Recording", "IAB9-17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(184) must be(VponUniversalCategory(184, "Hobbies & Interests", "Investors & Patents", "IAB9-18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(185) must be(VponUniversalCategory(185, "Hobbies & Interests", "Jewelry Making", "IAB9-19"))
    UniversalCategoryMapping.findVponUniversalCategoryById(186) must be(VponUniversalCategory(186, "Hobbies & Interests", "Magic & Illusion", "IAB9-20"))
    UniversalCategoryMapping.findVponUniversalCategoryById(187) must be(VponUniversalCategory(187, "Hobbies & Interests", "Needlework", "IAB9-21"))
    UniversalCategoryMapping.findVponUniversalCategoryById(188) must be(VponUniversalCategory(188, "Hobbies & Interests", "Painting", "IAB9-22"))
    UniversalCategoryMapping.findVponUniversalCategoryById(189) must be(VponUniversalCategory(189, "Hobbies & Interests", "Photography", "IAB9-23"))
    UniversalCategoryMapping.findVponUniversalCategoryById(190) must be(VponUniversalCategory(190, "Hobbies & Interests", "Radio", "IAB9-24"))
    UniversalCategoryMapping.findVponUniversalCategoryById(191) must be(VponUniversalCategory(191, "Hobbies & Interests", "Roleplaying Games", "IAB9-25"))
    UniversalCategoryMapping.findVponUniversalCategoryById(192) must be(VponUniversalCategory(192, "Hobbies & Interests", "Sci-Fi & Fantasy", "IAB9-26"))
    UniversalCategoryMapping.findVponUniversalCategoryById(193) must be(VponUniversalCategory(193, "Hobbies & Interests", "Scrapbooking", "IAB9-27"))
    UniversalCategoryMapping.findVponUniversalCategoryById(194) must be(VponUniversalCategory(194, "Hobbies & Interests", "Screenwriting", "IAB9-28"))
    UniversalCategoryMapping.findVponUniversalCategoryById(195) must be(VponUniversalCategory(195, "Hobbies & Interests", "Stamps & Coins", "IAB9-29"))
    UniversalCategoryMapping.findVponUniversalCategoryById(196) must be(VponUniversalCategory(196, "Hobbies & Interests", "Video & Computer Games", "IAB9-30"))
    UniversalCategoryMapping.findVponUniversalCategoryById(197) must be(VponUniversalCategory(197, "Hobbies & Interests", "Woodworking", "IAB9-31"))
    UniversalCategoryMapping.findVponUniversalCategoryById(10) must be(VponUniversalCategory(10, "Hobbies & Interests", "", "IAB10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(198) must be(VponUniversalCategory(198, "Hobbies & Interests", "Appliances", "IAB10-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(199) must be(VponUniversalCategory(199, "Hobbies & Interests", "Entertaining", "IAB10-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(200) must be(VponUniversalCategory(200, "Hobbies & Interests", "Environmental Safety", "IAB10-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(201) must be(VponUniversalCategory(201, "Hobbies & Interests", "Gardening", "IAB10-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(202) must be(VponUniversalCategory(202, "Hobbies & Interests", "Home Repair", "IAB10-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(203) must be(VponUniversalCategory(203, "Hobbies & Interests", "Home Theater", "IAB10-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(204) must be(VponUniversalCategory(204, "Hobbies & Interests", "Interior Decorating", "IAB10-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(205) must be(VponUniversalCategory(205, "Hobbies & Interests", "Landscaping", "IAB10-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(206) must be(VponUniversalCategory(206, "Hobbies & Interests", "Remodeling & Construction", "IAB10-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(11) must be(VponUniversalCategory(11, "Law, Gov't & Politics", "", "IAB11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(207) must be(VponUniversalCategory(207, "Law, Gov't & Politics", "Immigration", "IAB11-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(208) must be(VponUniversalCategory(208, "Law, Gov't & Politics", "Legal Issues", "IAB11-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(209) must be(VponUniversalCategory(209, "Law, Gov't & Politics", "U.S. Government Resources", "IAB11-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(210) must be(VponUniversalCategory(210, "Law, Gov't & Politics", "Politics", "IAB11-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(211) must be(VponUniversalCategory(211, "Law, Gov't & Politics", "Commentary", "IAB11-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(12) must be(VponUniversalCategory(12, "News", "", "IAB12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(212) must be(VponUniversalCategory(212, "News", "International News", "IAB12-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(213) must be(VponUniversalCategory(213, "News", "National News", "IAB12-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(214) must be(VponUniversalCategory(214, "News", "Local News", "IAB12-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(13) must be(VponUniversalCategory(13, "Personal Finance", "", "IAB13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(215) must be(VponUniversalCategory(215, "Personal Finance", "Beginning Investing", "IAB13-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(216) must be(VponUniversalCategory(216, "Personal Finance", "Credit/Debt & Loans", "IAB13-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(217) must be(VponUniversalCategory(217, "Personal Finance", "Financial News", "IAB13-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(218) must be(VponUniversalCategory(218, "Personal Finance", "Financial Planning", "IAB13-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(219) must be(VponUniversalCategory(219, "Personal Finance", "Hedge Fund", "IAB13-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(220) must be(VponUniversalCategory(220, "Personal Finance", "Insurance", "IAB13-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(221) must be(VponUniversalCategory(221, "Personal Finance", "Investing", "IAB13-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(222) must be(VponUniversalCategory(222, "Personal Finance", "Mutual Funds", "IAB13-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(223) must be(VponUniversalCategory(223, "Personal Finance", "Options", "IAB13-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(224) must be(VponUniversalCategory(224, "Personal Finance", "Retirement Planning", "IAB13-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(225) must be(VponUniversalCategory(225, "Personal Finance", "Stocks", "IAB13-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(226) must be(VponUniversalCategory(226, "Personal Finance", "Tax Planning", "IAB13-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(14) must be(VponUniversalCategory(14, "Society", "", "IAB14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(227) must be(VponUniversalCategory(227, "Society", "Dating", "IAB14-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(228) must be(VponUniversalCategory(228, "Society", "Divorce Support", "IAB14-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(229) must be(VponUniversalCategory(229, "Society", "Gay Life", "IAB14-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(230) must be(VponUniversalCategory(230, "Society", "Marriage", "IAB14-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(231) must be(VponUniversalCategory(231, "Society", "Senior Living", "IAB14-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(232) must be(VponUniversalCategory(232, "Society", "Teens", "IAB14-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(233) must be(VponUniversalCategory(233, "Society", "Weddings", "IAB14-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(234) must be(VponUniversalCategory(234, "Society", "Ethnic Specific", "IAB14-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(15) must be(VponUniversalCategory(15, "Science", "", "IAB15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(235) must be(VponUniversalCategory(235, "Science", "Astrology", "IAB15-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(236) must be(VponUniversalCategory(236, "Science", "Biology", "IAB15-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(237) must be(VponUniversalCategory(237, "Science", "Chemistry", "IAB15-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(238) must be(VponUniversalCategory(238, "Science", "Geology", "IAB15-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(239) must be(VponUniversalCategory(239, "Science", "Paranormal Phenomena", "IAB15-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(240) must be(VponUniversalCategory(240, "Science", "Physics", "IAB15-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(241) must be(VponUniversalCategory(241, "Science", "Space/Astronomy", "IAB15-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(242) must be(VponUniversalCategory(242, "Science", "Geography", "IAB15-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(243) must be(VponUniversalCategory(243, "Science", "Botany", "IAB15-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(244) must be(VponUniversalCategory(244, "Science", "Weather", "IAB15-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(16) must be(VponUniversalCategory(16, "Pets", "", "IAB16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(245) must be(VponUniversalCategory(245, "Pets", "Aquariums", "IAB16-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(246) must be(VponUniversalCategory(246, "Pets", "Birds", "IAB16-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(247) must be(VponUniversalCategory(247, "Pets", "Cats", "IAB16-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(248) must be(VponUniversalCategory(248, "Pets", "Dogs", "IAB16-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(249) must be(VponUniversalCategory(249, "Pets", "Large Animals", "IAB16-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(250) must be(VponUniversalCategory(250, "Pets", "Reptiles", "IAB16-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(251) must be(VponUniversalCategory(251, "Pets", "Veterinary Medicine", "IAB16-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(17) must be(VponUniversalCategory(17, "Sports", "", "IAB17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(252) must be(VponUniversalCategory(252, "Sports", "Auto Racing", "IAB17-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(253) must be(VponUniversalCategory(253, "Sports", "Baseball", "IAB17-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(254) must be(VponUniversalCategory(254, "Sports", "Bicycling", "IAB17-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(255) must be(VponUniversalCategory(255, "Sports", "Bodybuilding", "IAB17-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(256) must be(VponUniversalCategory(256, "Sports", "Boxing", "IAB17-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(257) must be(VponUniversalCategory(257, "Sports", "Canoeing/Kayaking", "IAB17-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(258) must be(VponUniversalCategory(258, "Sports", "Cheerleading", "IAB17-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(259) must be(VponUniversalCategory(259, "Sports", "Climbing", "IAB17-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(260) must be(VponUniversalCategory(260, "Sports", "Cricket", "IAB17-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(261) must be(VponUniversalCategory(261, "Sports", "Figure Skating", "IAB17-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(262) must be(VponUniversalCategory(262, "Sports", "Fly Fishing", "IAB17-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(263) must be(VponUniversalCategory(263, "Sports", "Football", "IAB17-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(264) must be(VponUniversalCategory(264, "Sports", "Freshwater Fishing", "IAB17-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(265) must be(VponUniversalCategory(265, "Sports", "Game & Fish", "IAB17-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(266) must be(VponUniversalCategory(266, "Sports", "Golf", "IAB17-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(267) must be(VponUniversalCategory(267, "Sports", "Horse Racing", "IAB17-16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(268) must be(VponUniversalCategory(268, "Sports", "Horses", "IAB17-17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(269) must be(VponUniversalCategory(269, "Sports", "Hunting/Shooting", "IAB17-18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(270) must be(VponUniversalCategory(270, "Sports", "Inline Skating", "IAB17-19"))
    UniversalCategoryMapping.findVponUniversalCategoryById(271) must be(VponUniversalCategory(271, "Sports", "Martial Arts", "IAB17-20"))
    UniversalCategoryMapping.findVponUniversalCategoryById(272) must be(VponUniversalCategory(272, "Sports", "Mountain Biking", "IAB17-21"))
    UniversalCategoryMapping.findVponUniversalCategoryById(273) must be(VponUniversalCategory(273, "Sports", "NASCAR Racing", "IAB17-22"))
    UniversalCategoryMapping.findVponUniversalCategoryById(274) must be(VponUniversalCategory(274, "Sports", "Olympics", "IAB17-23"))
    UniversalCategoryMapping.findVponUniversalCategoryById(275) must be(VponUniversalCategory(275, "Sports", "Paintball", "IAB17-24"))
    UniversalCategoryMapping.findVponUniversalCategoryById(276) must be(VponUniversalCategory(276, "Sports", "Power & Motorcycles", "IAB17-25"))
    UniversalCategoryMapping.findVponUniversalCategoryById(277) must be(VponUniversalCategory(277, "Sports", "Pro Basketball", "IAB17-26"))
    UniversalCategoryMapping.findVponUniversalCategoryById(278) must be(VponUniversalCategory(278, "Sports", "Pro Ice Hockey", "IAB17-27"))
    UniversalCategoryMapping.findVponUniversalCategoryById(279) must be(VponUniversalCategory(279, "Sports", "Rodeo", "IAB17-28"))
    UniversalCategoryMapping.findVponUniversalCategoryById(280) must be(VponUniversalCategory(280, "Sports", "Rugby", "IAB17-29"))
    UniversalCategoryMapping.findVponUniversalCategoryById(281) must be(VponUniversalCategory(281, "Sports", "Running/Jogging", "IAB17-30"))
    UniversalCategoryMapping.findVponUniversalCategoryById(282) must be(VponUniversalCategory(282, "Sports", "Sailing", "IAB17-31"))
    UniversalCategoryMapping.findVponUniversalCategoryById(283) must be(VponUniversalCategory(283, "Sports", "Saltwater Fishing", "IAB17-32"))
    UniversalCategoryMapping.findVponUniversalCategoryById(284) must be(VponUniversalCategory(284, "Sports", "Scuba Diving", "IAB17-33"))
    UniversalCategoryMapping.findVponUniversalCategoryById(285) must be(VponUniversalCategory(285, "Sports", "Skateboarding", "IAB17-34"))
    UniversalCategoryMapping.findVponUniversalCategoryById(286) must be(VponUniversalCategory(286, "Sports", "Skiing", "IAB17-35"))
    UniversalCategoryMapping.findVponUniversalCategoryById(287) must be(VponUniversalCategory(287, "Sports", "Snowboarding", "IAB17-36"))
    UniversalCategoryMapping.findVponUniversalCategoryById(288) must be(VponUniversalCategory(288, "Sports", "Surfing/Bodyboarding", "IAB17-37"))
    UniversalCategoryMapping.findVponUniversalCategoryById(289) must be(VponUniversalCategory(289, "Sports", "Swimming", "IAB17-38"))
    UniversalCategoryMapping.findVponUniversalCategoryById(290) must be(VponUniversalCategory(290, "Sports", "Table Tennis/Ping-Pong", "IAB17-39"))
    UniversalCategoryMapping.findVponUniversalCategoryById(291) must be(VponUniversalCategory(291, "Sports", "Tennis", "IAB17-40"))
    UniversalCategoryMapping.findVponUniversalCategoryById(292) must be(VponUniversalCategory(292, "Sports", "Volleyball", "IAB17-41"))
    UniversalCategoryMapping.findVponUniversalCategoryById(293) must be(VponUniversalCategory(293, "Sports", "Walking", "IAB17-42"))
    UniversalCategoryMapping.findVponUniversalCategoryById(294) must be(VponUniversalCategory(294, "Sports", "Waterski/Wakeboard", "IAB17-43"))
    UniversalCategoryMapping.findVponUniversalCategoryById(295) must be(VponUniversalCategory(295, "Sports", "World Soccer", "IAB17-44"))
    UniversalCategoryMapping.findVponUniversalCategoryById(18) must be(VponUniversalCategory(18, "Style & Fashion", "", "IAB18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(296) must be(VponUniversalCategory(296, "Style & Fashion", "Beauty", "IAB18-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(297) must be(VponUniversalCategory(297, "Style & Fashion", "Body Art", "IAB18-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(298) must be(VponUniversalCategory(298, "Style & Fashion", "Fashion", "IAB18-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(299) must be(VponUniversalCategory(299, "Style & Fashion", "Jewelry", "IAB18-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(300) must be(VponUniversalCategory(300, "Style & Fashion", "Clothing", "IAB18-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(301) must be(VponUniversalCategory(301, "Style & Fashion", "Accessories", "IAB18-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(19) must be(VponUniversalCategory(19, "Technology & Computing", "", "IAB19"))
    UniversalCategoryMapping.findVponUniversalCategoryById(302) must be(VponUniversalCategory(302, "Technology & Computing", "3-D Graphics", "IAB19-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(303) must be(VponUniversalCategory(303, "Technology & Computing", "Animation", "IAB19-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(304) must be(VponUniversalCategory(304, "Technology & Computing", "Antivirus Software", "IAB19-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(305) must be(VponUniversalCategory(305, "Technology & Computing", "C/C++", "IAB19-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(306) must be(VponUniversalCategory(306, "Technology & Computing", "Cameras & Camcorders", "IAB19-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(307) must be(VponUniversalCategory(307, "Technology & Computing", "Cell Phones", "IAB19-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(308) must be(VponUniversalCategory(308, "Technology & Computing", "Computer Certification", "IAB19-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(309) must be(VponUniversalCategory(309, "Technology & Computing", "Computer Networking", "IAB19-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(310) must be(VponUniversalCategory(310, "Technology & Computing", "Computer Peripherals", "IAB19-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(311) must be(VponUniversalCategory(311, "Technology & Computing", "Computer Reviews", "IAB19-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(312) must be(VponUniversalCategory(312, "Technology & Computing", "Data Centers", "IAB19-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(313) must be(VponUniversalCategory(313, "Technology & Computing", "Databases", "IAB19-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(314) must be(VponUniversalCategory(314, "Technology & Computing", "Desktop Publishing", "IAB19-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(315) must be(VponUniversalCategory(315, "Technology & Computing", "Desktop Video", "IAB19-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(316) must be(VponUniversalCategory(316, "Technology & Computing", "Email", "IAB19-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(317) must be(VponUniversalCategory(317, "Technology & Computing", "Graphics Software", "IAB19-16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(318) must be(VponUniversalCategory(318, "Technology & Computing", "Home Video/DVD", "IAB19-17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(319) must be(VponUniversalCategory(319, "Technology & Computing", "Internet Technology", "IAB19-18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(320) must be(VponUniversalCategory(320, "Technology & Computing", "Java", "IAB19-19"))
    UniversalCategoryMapping.findVponUniversalCategoryById(321) must be(VponUniversalCategory(321, "Technology & Computing", "JavaScript", "IAB19-20"))
    UniversalCategoryMapping.findVponUniversalCategoryById(322) must be(VponUniversalCategory(322, "Technology & Computing", "Mac Support", "IAB19-21"))
    UniversalCategoryMapping.findVponUniversalCategoryById(323) must be(VponUniversalCategory(323, "Technology & Computing", "MP3/MIDI", "IAB19-22"))
    UniversalCategoryMapping.findVponUniversalCategoryById(324) must be(VponUniversalCategory(324, "Technology & Computing", "Net Conferencing", "IAB19-23"))
    UniversalCategoryMapping.findVponUniversalCategoryById(325) must be(VponUniversalCategory(325, "Technology & Computing", "Net for Beginners", "IAB19-24"))
    UniversalCategoryMapping.findVponUniversalCategoryById(326) must be(VponUniversalCategory(326, "Technology & Computing", "Network Security", "IAB19-25"))
    UniversalCategoryMapping.findVponUniversalCategoryById(327) must be(VponUniversalCategory(327, "Technology & Computing", "Palmtops/PDAs", "IAB19-26"))
    UniversalCategoryMapping.findVponUniversalCategoryById(328) must be(VponUniversalCategory(328, "Technology & Computing", "PC Support", "IAB19-27"))
    UniversalCategoryMapping.findVponUniversalCategoryById(329) must be(VponUniversalCategory(329, "Technology & Computing", "Portable", "IAB19-28"))
    UniversalCategoryMapping.findVponUniversalCategoryById(330) must be(VponUniversalCategory(330, "Technology & Computing", "Entertainment", "IAB19-29"))
    UniversalCategoryMapping.findVponUniversalCategoryById(331) must be(VponUniversalCategory(331, "Technology & Computing", "Shareware/Freeware", "IAB19-30"))
    UniversalCategoryMapping.findVponUniversalCategoryById(332) must be(VponUniversalCategory(332, "Technology & Computing", "Unix", "IAB19-31"))
    UniversalCategoryMapping.findVponUniversalCategoryById(333) must be(VponUniversalCategory(333, "Technology & Computing", "Visual Basic", "IAB19-32"))
    UniversalCategoryMapping.findVponUniversalCategoryById(334) must be(VponUniversalCategory(334, "Technology & Computing", "Web Clip Art", "IAB19-33"))
    UniversalCategoryMapping.findVponUniversalCategoryById(335) must be(VponUniversalCategory(335, "Technology & Computing", "Web Design/HTML", "IAB19-34"))
    UniversalCategoryMapping.findVponUniversalCategoryById(336) must be(VponUniversalCategory(336, "Technology & Computing", "Web Search", "IAB19-35"))
    UniversalCategoryMapping.findVponUniversalCategoryById(337) must be(VponUniversalCategory(337, "Technology & Computing", "Windows", "IAB19-36"))
    UniversalCategoryMapping.findVponUniversalCategoryById(20) must be(VponUniversalCategory(20, "Travel", "", "IAB20"))
    UniversalCategoryMapping.findVponUniversalCategoryById(338) must be(VponUniversalCategory(338, "Travel", "Adventure Travel", "IAB20-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(339) must be(VponUniversalCategory(339, "Travel", "Africa", "IAB20-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(340) must be(VponUniversalCategory(340, "Travel", "Air Travel", "IAB20-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(341) must be(VponUniversalCategory(341, "Travel", "Australia & New Zealand", "IAB20-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(342) must be(VponUniversalCategory(342, "Travel", "Bed & Breakfasts", "IAB20-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(343) must be(VponUniversalCategory(343, "Travel", "Budget Travel", "IAB20-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(344) must be(VponUniversalCategory(344, "Travel", "Business Travel", "IAB20-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(345) must be(VponUniversalCategory(345, "Travel", "By US Locale", "IAB20-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(346) must be(VponUniversalCategory(346, "Travel", "Camping", "IAB20-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(347) must be(VponUniversalCategory(347, "Travel", "Canada", "IAB20-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(348) must be(VponUniversalCategory(348, "Travel", "Caribbean", "IAB20-11"))
    UniversalCategoryMapping.findVponUniversalCategoryById(349) must be(VponUniversalCategory(349, "Travel", "Cruises", "IAB20-12"))
    UniversalCategoryMapping.findVponUniversalCategoryById(350) must be(VponUniversalCategory(350, "Travel", "Eastern Europe", "IAB20-13"))
    UniversalCategoryMapping.findVponUniversalCategoryById(351) must be(VponUniversalCategory(351, "Travel", "Europe", "IAB20-14"))
    UniversalCategoryMapping.findVponUniversalCategoryById(352) must be(VponUniversalCategory(352, "Travel", "France", "IAB20-15"))
    UniversalCategoryMapping.findVponUniversalCategoryById(353) must be(VponUniversalCategory(353, "Travel", "Greece", "IAB20-16"))
    UniversalCategoryMapping.findVponUniversalCategoryById(354) must be(VponUniversalCategory(354, "Travel", "Honeymoons/Getaways", "IAB20-17"))
    UniversalCategoryMapping.findVponUniversalCategoryById(355) must be(VponUniversalCategory(355, "Travel", "Hotels", "IAB20-18"))
    UniversalCategoryMapping.findVponUniversalCategoryById(356) must be(VponUniversalCategory(356, "Travel", "Italy", "IAB20-19"))
    UniversalCategoryMapping.findVponUniversalCategoryById(357) must be(VponUniversalCategory(357, "Travel", "Japan", "IAB20-20"))
    UniversalCategoryMapping.findVponUniversalCategoryById(358) must be(VponUniversalCategory(358, "Travel", "Mexico & Central America", "IAB20-21"))
    UniversalCategoryMapping.findVponUniversalCategoryById(359) must be(VponUniversalCategory(359, "Travel", "National Parks", "IAB20-22"))
    UniversalCategoryMapping.findVponUniversalCategoryById(360) must be(VponUniversalCategory(360, "Travel", "South America", "IAB20-23"))
    UniversalCategoryMapping.findVponUniversalCategoryById(361) must be(VponUniversalCategory(361, "Travel", "Spas", "IAB20-24"))
    UniversalCategoryMapping.findVponUniversalCategoryById(362) must be(VponUniversalCategory(362, "Travel", "Theme Parks", "IAB20-25"))
    UniversalCategoryMapping.findVponUniversalCategoryById(363) must be(VponUniversalCategory(363, "Travel", "Traveling with Kids", "IAB20-26"))
    UniversalCategoryMapping.findVponUniversalCategoryById(364) must be(VponUniversalCategory(364, "Travel", "United Kingdom", "IAB20-27"))
    UniversalCategoryMapping.findVponUniversalCategoryById(21) must be(VponUniversalCategory(21, "Real Estate", "", "IAB21"))
    UniversalCategoryMapping.findVponUniversalCategoryById(365) must be(VponUniversalCategory(365, "Real Estate", "Apartments", "IAB21-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(366) must be(VponUniversalCategory(366, "Real Estate", "Architects", "IAB21-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(367) must be(VponUniversalCategory(367, "Real Estate", "Buying/Selling Homes", "IAB21-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(22) must be(VponUniversalCategory(22, "Shopping", "", "IAB22"))
    UniversalCategoryMapping.findVponUniversalCategoryById(368) must be(VponUniversalCategory(368, "Shopping", "Contests & Freebies", "IAB22-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(369) must be(VponUniversalCategory(369, "Shopping", "Couponing", "IAB22-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(370) must be(VponUniversalCategory(370, "Shopping", "Comparison", "IAB22-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(371) must be(VponUniversalCategory(371, "Shopping", "Engines", "IAB22-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(23) must be(VponUniversalCategory(23, "Religion & Spirituality", "", "IAB23"))
    UniversalCategoryMapping.findVponUniversalCategoryById(372) must be(VponUniversalCategory(372, "Religion & Spirituality", "Alternative Religions", "IAB23-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(373) must be(VponUniversalCategory(373, "Religion & Spirituality", "Atheism/Agnosticism", "IAB23-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(374) must be(VponUniversalCategory(374, "Religion & Spirituality", "Buddhism", "IAB23-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(375) must be(VponUniversalCategory(375, "Religion & Spirituality", "Catholicism", "IAB23-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(376) must be(VponUniversalCategory(376, "Religion & Spirituality", "Christianity", "IAB23-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(377) must be(VponUniversalCategory(377, "Religion & Spirituality", "Hinduism", "IAB23-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(378) must be(VponUniversalCategory(378, "Religion & Spirituality", "Islam", "IAB23-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(379) must be(VponUniversalCategory(379, "Religion & Spirituality", "Judaism", "IAB23-8"))
    UniversalCategoryMapping.findVponUniversalCategoryById(380) must be(VponUniversalCategory(380, "Religion & Spirituality", "Latter-Day Saints", "IAB23-9"))
    UniversalCategoryMapping.findVponUniversalCategoryById(381) must be(VponUniversalCategory(381, "Religion & Spirituality", "Pagan/Wiccan", "IAB23-10"))
    UniversalCategoryMapping.findVponUniversalCategoryById(24) must be(VponUniversalCategory(24, "Uncategorized", "", "IAB24"))
    UniversalCategoryMapping.findVponUniversalCategoryById(25) must be(VponUniversalCategory(25, "Non-Standard Content", "", "IAB25"))
    UniversalCategoryMapping.findVponUniversalCategoryById(382) must be(VponUniversalCategory(382, "Non-Standard Content", "Unmoderated UGC", "IAB25-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(383) must be(VponUniversalCategory(383, "Non-Standard Content", "Extreme Graphic/Explicit Violence", "IAB25-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(384) must be(VponUniversalCategory(384, "Non-Standard Content", "Pornography", "IAB25-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(385) must be(VponUniversalCategory(385, "Non-Standard Content", "Profane Content", "IAB25-4"))
    UniversalCategoryMapping.findVponUniversalCategoryById(386) must be(VponUniversalCategory(386, "Non-Standard Content", "Hate Content", "IAB25-5"))
    UniversalCategoryMapping.findVponUniversalCategoryById(387) must be(VponUniversalCategory(387, "Non-Standard Content", "Under Construction", "IAB25-6"))
    UniversalCategoryMapping.findVponUniversalCategoryById(388) must be(VponUniversalCategory(388, "Non-Standard Content", "Incentivized", "IAB25-7"))
    UniversalCategoryMapping.findVponUniversalCategoryById(389) must be(VponUniversalCategory(389, "Illegal Content", "Illegal Content", "IAB26-1"))
    UniversalCategoryMapping.findVponUniversalCategoryById(26) must be(VponUniversalCategory(26, "Illegal Content", "", "IAB26"))
    UniversalCategoryMapping.findVponUniversalCategoryById(390) must be(VponUniversalCategory(390, "Illegal Content", "Warez", "IAB26-2"))
    UniversalCategoryMapping.findVponUniversalCategoryById(391) must be(VponUniversalCategory(391, "Illegal Content", "Spyware/Malware", "IAB26-3"))
    UniversalCategoryMapping.findVponUniversalCategoryById(392) must be(VponUniversalCategory(392, "Illegal Content", "Copyright Infringement", "IAB26-4"))
  }

  it must "find all VponUniversalCategories properly" in {
    UniversalCategoryMapping.findAllVponUniversalCategories.size must be(392)
  }
}
